= Semantic Parsing with Kotlin (Sandbox)

link:https://github.com/github/semantic[Semantic] is a Github project for parsing, analyzing, and comparing source code.
It is language agnostic and supports Js/Ts/Python/Ruby and many more languages.

One of the things it can do is to transform code in the supported languages to a common json format, see link:https://github.com/github/semantic/blob/master/docs/examples.md[docs/examples]. That is the format that Github uses to provide code navigation.

Maybe we can also use this format to generate metrics for any of the languages Semantic supports.

The project is divided into two parts:

* parser: for parsing semantic AST files and generate McCabe complexity from it.
* language-examples: where we store code esxamples to analyze with semantic and transform into json files

== Results

Semantic provides two different output-formats: `--json-symbols` and `--sexpression`.

`--json-symbols` creates a `.json` file that contains the location (start line/column and end line/column) of all "Class", "Function", "Method" or "Call" (function or method call) symbols. It's nice for linking functions/methods with the place they get called from. Incidentally that's what Github uses it for. It's not possible to calculate metrics from this limited information though.

`--sexpression` creates a nice abstract syntax tree (AST) of the code. Here's an link:https://github.com/github/semantic/blob/master/docs/examples.md[example] if you don't want to run the script further below. It's great because the structures are nested when the code is nested and the syntax terms are generalized across all supported languages. It is however missing the location in the file (start line/column and end line/column). The AST is also missing the actual symbol values (name of the variable, function etc.). We cannot calculate how long the average if statement is like this. We cannot calculate the amount of comments in the code. We can however calculate the McCabe complexity and similar nice things.

`--show` is another output format that is unfortunately not guaranteed to stay stable. It contains the symbol values (name of the variable, function etc.) but no location either.

To generate more complex metrics we'd have to either tokenize the actual file contents and match them to the `--sexpression` output (without identifiers) or the `--show` output (which can change theoretically any minute).

== Getting Started Parser

* Run tests `./gradlew test`
* Pass files via command-line: `./gradlew run --args "file.json"`

== Getting Started Language Examples

=== Via Docker

* In your (Git) bash run `cd language-examples`, next `./analyze.sh`
* Then take a look at the resulting files in `_analyzed`.